### ISSUE TITLE
Icons don't show up

### ISSUE THREAD

**Issue by glocq** [UntimelyCreation/typst-neat-cv#1]
Compiling my CV works fine, except for the phone, email, github etc. icons, which are replaced with boxes with a cross inside. I did add the option `--font-path src/fonts/` to the typst command, to no avail.

Great template otherwise!

**Comment by UntimelyCreation** [comment]
Hey, thank you for the kind words!
That's my bad, I forgot to include the Symbols Nerd Font that the template uses to render those icons.
I've just pushed a fix that should resolve this. Please tell me if it works for you.
Cheers!

**Comment by glocq** [comment]
Perfect, it works! Thank you.
