### ISSUE TITLE
Add progress bar to technical skills

### ISSUE THREAD

**Issue by Karstack-overflow** [UntimelyCreation/typst-neat-cv#2]
i have added a progressbar under the technical skills. i think this is a nice visual representation of the skills. i would like to share the code of this.
```
#let progress_bar(
  progress,
) = {
  // Fix for https://github.com/typst/typst/issues/3826
  if progress == 0% {
    progress = 0.1%
  }

  set block(above: 8pt, below: 8pt, spacing: 0pt)
  set par(leading: 0em)
  let light-accent = chosenAccentColor.lighten(20%)
  let grad-accent = chosenAccentColor.darken(20%)

  context {
    rect(
      height: 8pt,
      width: 100%,
      stroke: chosenAccentColor,
      fill: gradient.linear(
        (light-accent, 0%),
        (grad-accent, progress),
        (white, progress),
        (white, 100%),  
      ),
      
    )
  }
}

#let cvSkill(
    type: "Type",
    tags: (),
    progress: none,
) = {
    skillTypeStyle(type)
    v(-1mm)
    tagListStyle(tags)
    if progress != none {
        v(1mm)
        progress_bar(progress)
    }
}
```
maybe you can include it to your template
![grafik](https://github.com/UntimelyCreation/typst-neat-cv/assets/76392699/696c0139-1075-4784-a805-66f04c21a971)

**Comment by UntimelyCreation** [comment]
Hey there!
Thanks for sharing your code, adding visual representation is a nice idea.
I have one comment: if the progress bar represents all of your programming skills at once like your screenshot suggests, I'm not sure it helps give a measure of your proficiency. I think it would be better to add one bar per skill (similar to the language section), but that may take up a lot of valuable space.
In any case, I do not plan on adding any features currently: I like the template being fairly minimal as it is right now.
If I change my mind, I'll be sure to keep you posted.
Cheers!

**Comment by Karstack-overflow** [comment]
Hey, 
Your template is really beautiful and minimalistic. It drew me more into typst to learn it. Thanks for the answer.
